apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deploymen
spec:
  replicas: 1
  selector:
    matchLabels:
       app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image: ylakshmisadhika/vprofile:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
