apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
       app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image: registry.kube-system.svc.cluster.local:5000/vprofile:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
