apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deploymen
spec:
  replicas: 1
  selector:
    matchLabels:
       app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image: localhost:5000/vprofile:<tag>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
